explainer_saving_dir: ''
explainer_saving_name: 'pgexplainer.pth'
explanation_result_dir: ''
sparsity: 0.5

param:
  ba_shapes:
    ex_learning_rate: 0.001
    ex_epochs: 20
    coff_size: 0.01
    coff_ent: 0.01
    t0: 5.0
    t1: 0.1
    undirected: True
    sample_bias: 0