explanation_result_dir: ''
max_ex_size: 5

param:
  ba_shapes:
    rollout: 20
    high2low: True
    c_puct: 10.0
    min_atoms: 5
    expand_atoms: 20
    reward_method: 'Nc_mc_l_shapley'
    subgraph_building_method: 'split'
    verbose: True